apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tugger-mutate
webhooks:
- name: tugger-mutate.jainishshah17.com
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  clientConfig:
    url: "https://5eb92435.ngrok.io/mutate"
#    service:
#      name: tugger-svc
#      namespace: default
#      path: "/mutate"