apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: tugger-validate
webhooks:
- name: tugger-validate.jainishshah17.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    url: "https://5eb92435.ngrok.io/validate"
#    service:
#      name: tugger-svc
#      namespace: default
#      path: "/validate"