apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tugger-deployment
  labels:
    app: tugger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tugger
    spec:
      containers:
      - name: tugger
        image: jainishshah17/tugger:0.0.5
        imagePullPolicy: Always
        env:
          - name: DOCKER_REGISTRY_URL
            value: "jainishshah17"
          - name: REGISTRY_SECRET_NAME
            value: 'regsecret'
          - name: WHITELIST_NAMESPACES
            value: "kube-system,default"
          - name: WHITELIST_REGISTRIES
            value: "jainishshah17"
        ports:
          - containerPort: 443
            name: https
        volumeMounts:
        - name: tls
          mountPath: /etc/admission-controller/tls
        resources: {}
      volumes:
        - name: tls
          secret:
            secretName: tugger-certs
